### ISSUE TITLE
how to get the results only for india country

### ISSUE THREAD

**Issue by dev-vishnupundhir** [cedricdelpoux/react-google-places-suggest#57]
now this npm give the suggestions for the all country how we can restrict it only for india

**Comment by xuopled** [comment]
You should take a look to the optional parameters listed [here](https://developers.google.com/maps/documentation/javascript/reference?hl=fr#AutocompletionRequest)

**Comment by alanpoon** [comment]
You can look at the type definition
autocompletionRequest={{
                                input: search,
                                componentRestrictions:{country:"in"}
                                // Optional options
                                // https://developers.google.com/maps/documentation/javascript/reference?hl=fr#AutocompletionRequest
                            }}
