### ISSUE TITLE
Add e.preventDefault for e.key === "Enter" in handleKeyDown-Method

### ISSUE THREAD

**Issue by dist0erbed** [cedricdelpoux/react-google-places-suggest#58]
First of all, thank you for your work, the component is a great help in our project :). 

There is just one little issue that is bothering us: We are using the component in a search form, for getting real addresses. 

The problem is, if you use the keyboard to select a place from the suggest dropdown and hit the enter key the wrapping form got submitted and triggers an error because the response from Google isn't ready.

The problem could be solved if you add a e.preventDefault if the enter key is hit in your handleKeyDown-Method.

If I'm missing something there, your help is highly appreciated.

**Comment by cedricdelpoux** [comment]
Thank you for reporting this. Could you make a PR to fix the problem? It would be very helpfull.
