### ISSUE TITLE
how to restrict it to a siingle country ?

### ISSUE THREAD

**Issue by Biplovkumar** [cedricdelpoux/react-google-places-suggest#63]
how to restrict it to a single country?

**Comment by cedricdelpoux** [comment]
Use `autocompletionRequest`  with optional options to achieve what you are looking for. Please checkout https://developers.google.com/maps/documentation/javascript/reference?hl=fr#AutocompletionRequest
```
autocompletionRequest={{
    input: search,
    // Optional options
    // https://developers.google.com/maps/documentation/javascript/reference?hl=fr#AutocompletionRequest
 }}
```
