### ISSUE TITLE
updatePredictions is invoked for each component instance on a page

### ISSUE THREAD

**Issue by germankhivrenko** [cedricdelpoux/react-google-places-suggest#65]
Hello, here is the problem: if we have more than one insatnce of the component on a page the predictions will be updated for each instance after changing one of the autocomplete requests. `updatePrediction` function is invoked for all instances in `UNSAFE_componentWillReceiveProps`.

**Comment by cedricdelpoux** [comment]
Thank you for reporting this. You will be welcome if you want to help on this :)

**Comment by germankhivrenko** [comment]
I've tried it on demo page and there was no bug. So I guess it's my mistake.

**Comment by germankhivrenko** [comment]
Here I am again) I have a suggestion to do a deep comparison of autocompletion requests on UNSAFE_componentWillReceiveProps. Because in the most of cases an autocompletion request comprises of type, value, etc and is generated every time on render. I could make a PR for that, just need your approvement. Thanks, in andvance

**Comment by cedricdelpoux** [comment]
Good idea. All PR are welcome :) Thank you

**Comment by germankhivrenko** [comment]
Hello, I wanted to push a branch for a PR but got a 403 error. I guess I
need access to push something. My account is github.com/germankhivrenko

пн, 18 мая 2020 г. в 15:37, Cédric Delpoux <notifications@github.com>:

**Comment by cedricdelpoux** [comment]
You need to fork the repo, update some code, push to your repo before opening a PR here

**Comment by germankhivrenko** [comment]
Sorry)) My first PR on github


сб, 23 мая 2020 г. в 16:08, Cédric Delpoux <notifications@github.com>:

**Comment by cedricdelpoux** [comment]
I merged it!. Thank you very much for your help 😀
