### ISSUE TITLE
Publish updates to npm

### ISSUE THREAD

**Issue by robertatcd** [cedricdelpoux/react-google-places-suggest#74]
Bonjour Cedric,

Looks like you're doing a great job keeping up with pull requests for dependency vulnerabilities/updates. But I think your package hasn't been updated at npm for a while?

Snyk is warning me about this vulnerability, introduced through the use of styled-components v2.4.1: https://snyk.io/test/npm/react-google-places-suggest/3.9.2

I see you addressed their pull request for that in September: https://github.com/cedricdelpoux/react-google-places-suggest/pull/72, which specifies the use of styled-components v4.0.0.

… but when I try to update the package via npm, the `package.json` that I get has `version: 3.9.2`, and 

```
  "dependencies": {
    "styled-components": "^2.4.0"
  },
```

I believe the solution is to bump up your version number, and republish to npm?

**Comment by cedricdelpoux** [comment]
Hi @robertatcd 

Sorry for the delay.
You are right. Thank you for reporting this.

I upgraded `styled-components` to the last version and published a `3.11.0` version
